# https://www.appveyor.com/docs/lang/nodejs-iojs/

environment:
  matrix:
    - nodejs_version: "7"
    - nodejs_version: "8"
    - nodejs_version: "9"
    - nodejs_version: "10"
    - nodejs_version: "11"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm run setup

test_script:
  - node --version
  - npm --version
  - npm run test

build: off
